(()=>{
'use strict';
const $=id=>document.getElementById(id);
const isAr=()=>document.documentElement.dir==='rtl'||document.documentElement.lang==='ar';
const tr=(en,ar)=>isAr()?ar:en;
const esc=s=>String(s??'').replace(/[&<>\"]/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','\"':'&quot;'}[m]));
let file=null,doc=null,busy=false,result=null;
function ui(){let b=$('klsGeomFeatures');if(!b){const host=$('klsDeepDimensions')||$('pvSelection')||$('planStatus')?.closest('.panel');if(!host)return null;b=document.createElement('div');b.id='klsGeomFeatures';host.appendChild(b)}b.style.cssText='margin-top:12px;padding:12px;border:1px solid #31506a;border-radius:14px;background:#0a151f';b.innerHTML=`<div style="display:flex;justify-content:space-between;gap:8px;align-items:center;flex-wrap:wrap"><strong>${tr('KLS Integrated Plan Model v24','نموذج المخطط المتكامل v24')}</strong><span id="g24State" class="chip warn">${tr('WAITING','انتظار')}</span></div><p id="g24Summary" class="tip">${tr('Builds one reviewable model from A-01 geometry, A-04 ceiling/lighting evidence and the dimension model.','يبني نموذجاً واحداً قابلاً للمراجعة من هندسة A-01 وأدلة السقف/الإضاءة في A-04 ونموذج الأبعاد.')}</p><div id="g24Facts" class="cards" style="grid-template-columns:repeat(auto-fit,minmax(135px,1fr));margin-top:8px"></div><canvas id="g24Preview" style="display:none;width:100%;max-height:480px;background:#fff;border-radius:10px;margin-top:10px"></canvas><div id="g24Layers" style="margin-top:10px"></div><div id="g24Evidence" style="margin-top:8px"></div><button id="g24Apply" class="btn good" style="margin-top:8px">${tr('Use integrated plan model','استخدام نموذج المخطط المتكامل')}</button>`;$('g24Apply').onclick=apply;return b}
function cards(items){const h=$('g24Facts');if(h)h.innerHTML=items.map(([a,b])=>`<div class="card"><small>${esc(a)}</small><strong>${esc(b)}</strong></div>`).join('')}
async function render(page,target=2400){const base=page.getViewport({scale:1}),s=Math.min(4.5,target/base.width),vp=page.getViewport({scale:s}),c=document.createElement('canvas');c.width=Math.round(vp.width);c.height=Math.round(vp.height);await page.render({canvasContext:c.getContext('2d',{alpha:false}),viewport:vp}).promise;return c}
function small(src,maxW=1100){const s=Math.min(1,maxW/src.width),c=document.createElement('canvas');c.width=Math.round(src.width*s);c.height=Math.round(src.height*s);c.getContext('2d').drawImage(src,0,0,c.width,c.height);return c}
function px(c){return c.getContext('2d').getImageData(0,0,c.width,c.height).data}
function masks(c){const d=px(c),dark=new Uint8Array(c.width*c.height),red=new Uint8Array(c.width*c.height);for(let i=0,p=0;i<d.length;i+=4,p++){const r=d[i],g=d[i+1],b=d[i+2];if(r<70&&g<70&&b<70&&Math.max(r,g,b)-Math.min(r,g,b)<25)dark[p]=1;if(r>130&&r>g*1.25&&r>b*1.18&&(r-g)>30)red[p]=1}return{dark,red,w:c.width,h:c.height}}
function wallEnvelope(M){const {dark,w,h}=M,roi={x0:.07,x1:.84,y0:.10,y1:.83},pts=[];for(let y=Math.floor(h*roi.y0);y<Math.floor(h*roi.y1);y+=3){let xs=[];for(let x=Math.floor(w*roi.x0);x<Math.floor(w*roi.x1);x++)if(dark[y*w+x])xs.push(x);if(xs.length>6){pts.push({x:xs[0],y});pts.push({x:xs[xs.length-1],y})}}for(let x=Math.floor(w*roi.x0);x<Math.floor(w*roi.x1);x+=3){let ys=[];for(let y=Math.floor(h*roi.y0);y<Math.floor(h*roi.y1);y++)if(dark[y*w+x])ys.push(y);if(ys.length>6){pts.push({x,y:ys[0]});pts.push({x,y:ys[ys.length-1]})}}pts.sort((a,b)=>a.x-b.x||a.y-b.y);const cross=(o,a,b)=>(a.x-o.x)*(b.y-o.y)-(a.y-o.y)*(b.x-o.x),lo=[];for(const p of pts){while(lo.length>=2&&cross(lo[lo.length-2],lo[lo.length-1],p)<=0)lo.pop();lo.push(p)}const up=[];for(let i=pts.length-1;i>=0;i--){const p=pts[i];while(up.length>=2&&cross(up[up.length-2],up[up.length-1],p)<=0)up.pop();up.push(p)}let hull=lo.slice(0,-1).concat(up.slice(0,-1));function dist(p,a,b){const A=b.y-a.y,B=a.x-b.x,C=b.x*a.y-a.x*b.y;return Math.abs(A*p.x+B*p.y+C)/Math.max(1,Math.hypot(A,B))}let changed=true;while(changed&&hull.length>4){changed=false;for(let i=0;i<hull.length;i++){const a=hull[(i-1+hull.length)%hull.length],p=hull[i],b=hull[(i+1)%hull.length];if(dist(p,a,b)<5){hull.splice(i,1);changed=true;break}}}return hull.map(p=>({x:p.x/w,y:p.y/h}))}
function connected(mask,w,h){const seen=new Uint8Array(mask.length),stack=[],out=[],x0=Math.floor(w*.06),x1=Math.floor(w*.86),y0=Math.floor(h*.08),y1=Math.floor(h*.84);for(let y=y0;y<y1;y++)for(let x=x0;x<x1;x++){const p=y*w+x;if(!mask[p]||seen[p])continue;seen[p]=1;stack.push(p);let n=0,minx=x,maxx=x,miny=y,maxy=y,sx=0,sy=0;while(stack.length){const q=stack.pop(),qx=q%w,qy=(q/w)|0;n++;sx+=qx;sy+=qy;minx=Math.min(minx,qx);maxx=Math.max(maxx,qx);miny=Math.min(miny,qy);maxy=Math.max(maxy,qy);for(const [dx,dy] of [[1,0],[-1,0],[0,1],[0,-1],[1,1],[-1,-1],[1,-1],[-1,1]]){const nx=qx+dx,ny=qy+dy;if(nx<x0||nx>=x1||ny<y0||ny>=y1)continue;const z=ny*w+nx;if(mask[z]&&!seen[z]){seen[z]=1;stack.push(z)}}}if(n>=3&&n<=4500)out.push({area:n,minx,maxx,miny,maxy,cx:sx/n,cy:sy/n,w:maxx-minx+1,h:maxy-miny+1})}return out}
function classifyRed(M){const comps=connected(M.red,M.w,M.h),tracks=[],symbols=[],other=[];for(const c of comps){const ar=Math.max(c.w,c.h)/Math.max(1,Math.min(c.w,c.h)),n={x:c.cx/M.w,y:c.cy/M.h,w:c.w/M.w,h:c.h/M.h,area:c.area};if(ar>=5&&Math.max(c.w,c.h)>=18){n.orientation=c.w>=c.h?'H':'V';tracks.push(n)}else if(c.w<=42&&c.h<=42&&c.area<=500)symbols.push(n);else other.push(n)}const keep=[];symbols.sort((a,b)=>b.area-a.area);for(const p of symbols){if(!keep.some(q=>Math.hypot(p.x-q.x,p.y-q.y)<.012))keep.push(p);if(keep.length>=120)break}return{tracks,symbols:keep,other}}
function detectGrid(M){const {dark,w,h}=M,xs=[],ys=[];for(let x=Math.floor(w*.10);x<Math.floor(w*.82);x+=2){let n=0;for(let y=Math.floor(h*.12);y<Math.floor(h*.76);y++)if(dark[y*w+x])n++;if(n>h*.28)xs.push(x/w)}for(let y=Math.floor(h*.12);y<Math.floor(h*.76);y+=2){let n=0;for(let x=Math.floor(w*.10);x<Math.floor(w*.82);x++)if(dark[y*w+x])n++;if(n>w*.30)ys.push(y/h)}const cluster=a=>{const o=[];for(const v of a){if(!o.length||Math.abs(v-o[o.length-1])>.006)o.push(v);else o[o.length-1]=(o[o.length-1]+v)/2}return o};return{x:cluster(xs),y:cluster(ys)}}
function segments(poly){return poly.map((a,i)=>{const b=poly[(i+1)%poly.length];return{id:'W'+String(i+1).padStart(2,'0'),start:a,end:b,lengthNormalized:Math.hypot(b.x-a.x,b.y-a.y),angleDeg:Math.atan2(b.y-a.y,b.x-a.x)*180/Math.PI}})}
function draw(src,poly,features){const out=$('g24Preview'),s=Math.min(1,1050/src.width);out.width=Math.round(src.width*s);out.height=Math.round(src.height*s);const q=out.getContext('2d');q.drawImage(src,0,0,out.width,out.height);q.lineWidth=4;if(poly.length>=3){q.beginPath();poly.forEach((p,i)=>{const x=p.x*out.width,y=p.y*out.height;i?q.lineTo(x,y):q.moveTo(x,y)});q.closePath();q.stroke()}q.lineWidth=2;features.tracks.slice(0,30).forEach(p=>q.strokeRect((p.x-p.w/2)*out.width,(p.y-p.h/2)*out.height,p.w*out.width,p.h*out.height));features.symbols.slice(0,80).forEach((p,i)=>{q.beginPath();q.arc(p.x*out.width,p.y*out.height,4,0,Math.PI*2);q.stroke();if(i<24)q.fillText(String(i+1),p.x*out.width+5,p.y*out.height-4)});out.style.display='block'}
function layerTable(poly){const rows=segments(poly).map(s=>`<tr><td>${s.id}</td><td>${s.start.x.toFixed(3)}, ${s.start.y.toFixed(3)}</td><td>${s.end.x.toFixed(3)}, ${s.end.y.toFixed(3)}</td><td>${s.lengthNormalized.toFixed(3)}</td><td>${Math.round(s.angleDeg)}°</td></tr>`).join('');$('g24Layers').innerHTML=`<div class="table"><table><thead><tr><th>${tr('Wall','حائط')}</th><th>${tr('Start','بداية')}</th><th>${tr('End','نهاية')}</th><th>${tr('Length N','الطول N')}</th><th>${tr('Angle','الزاوية')}</th></tr></thead><tbody>${rows}</tbody></table></div>`}
async function readSheet(pn){const p=await doc.getPage(pn),src=await render(p),sm=small(src),M=masks(sm);return{src,sm,M}}
async function run(){if(!file||busy)return;busy=true;ui();result=null;$('g24State').textContent=tr('BUILDING MODEL','بناء النموذج');$('g24State').className='chip warn';try{if(!window.pdfjsLib)throw Error('PDF engine unavailable');if(!doc){const data=new Uint8Array(await file.arrayBuffer());doc=await pdfjsLib.getDocument({data}).promise}if(doc.numPages<5)throw Error('A-01/A-04 mapping unavailable');$('g24Summary').textContent=tr('Reading A-01 wall envelope…','جاري قراءة حدود حوائط A-01…');const A1=await readSheet(2),poly=wallEnvelope(A1.M);$('g24Summary').textContent=tr('Reading A-04 lighting and ceiling evidence…','جاري قراءة أدلة الإضاءة والسقف في A-04…');const A4=await readSheet(5),features=classifyRed(A4.M),grid=detectGrid(A4.M),dim=window.KLS_DIMENSION_MODEL||null,status=dim?'mixed':'estimated';result={A1,A4,poly,features,grid,dim,status};cards([[tr('Wall vertices','نقاط حدود الحوائط'),poly.length],[tr('Wall segments','قطاعات الحوائط'),poly.length],[tr('Track-like red elements','عناصر حمراء شبيهة بالتراك'),features.tracks.length],[tr('Compact red symbols','رموز حمراء مدمجة'),features.symbols.length],[tr('Ceiling grid X','شبكة السقف X'),grid.x.length],[tr('Ceiling grid Y','شبكة السقف Y'),grid.y.length],[tr('Dimension calibration','معايرة الأبعاد'),dim?tr('Linked','مرتبطة'):tr('Pending review','بانتظار المراجعة')],[tr('Model status','حالة النموذج'),status.toUpperCase()]]);layerTable(poly);draw(A4.src,poly,features);const ev=[tr('A-01 remains the only base geometry authority.','تظل A-01 المرجع الأساسي الوحيد لهندسة الفراغ.'),tr('The wall envelope is no longer forced to four corners; it is stored as a simplified irregular polygon.','لم تعد حدود الحوائط مجبرة على أربعة أركان؛ بل تُحفظ كمضلع غير منتظم مبسط.'),tr('A-04 red geometry is split into elongated track-like candidates and compact symbol candidates instead of one mixed red list.','يتم تقسيم العناصر الحمراء في A-04 إلى مرشحات طويلة شبيهة بالتراك ورموز مدمجة بدلاً من قائمة حمراء مختلطة واحدة.'),tr('Classification remains evidence-based until A-00 legend matching confirms Track Light / Spotlight / Wire Rope semantics.','يظل التصنيف قائماً على الأدلة إلى أن يؤكد ربط Legend في A-00 معنى Track Light / Spotlight / Wire Rope.'),tr('No metre coordinates are invented without verified dimension calibration.','لا يتم اختلاق إحداثيات بالمتر دون معايرة أبعاد مؤكدة.')];$('g24Evidence').innerHTML=ev.map(x=>`<div class="tip">• ${esc(x)}</div>`).join('');$('g24State').textContent=tr('MODEL READY','النموذج جاهز');$('g24State').className='chip good';$('g24Summary').textContent=tr('Integrated plan model completed.','اكتمل نموذج المخطط المتكامل.')}catch(e){console.error(e);$('g24State').textContent=tr('ERROR','خطأ');$('g24Summary').textContent=tr('Integrated model failed: ','فشل النموذج المتكامل: ')+(e.message||e)}finally{busy=false}}
function apply(){if(!result?.poly?.length){alert(tr('No usable geometry yet.','لا توجد هندسة قابلة للاستخدام حتى الآن.'));return}window.KLS_ANALYSIS_MODEL={version:'24',sourceSheets:{geometry:'A-01',lighting:'A-04',legend:'A-00',artwork:'A-02'},status:result.status,coordinateSystem:result.dim?'normalized + dimension-linked':'normalized',geometry:{polygon:result.poly,segments:segments(result.poly)},dimensions:result.dim,ceiling:{grid:result.grid},lighting:{trackCandidates:result.features.tracks,symbolCandidates:result.features.symbols},evidence:{geometry:'A-01 dark wall envelope',lighting:'A-04 red geometry',dimensionModel:!!result.dim}};$('spaceGeometryState').textContent=tr('Integrated A-01/A-04 model created','تم إنشاء نموذج A-01/A-04 المتكامل');$('spaceConfidence').textContent=tr(result.dim?'Confidence: mixed':'Confidence: estimated',result.dim?'درجة الثقة: مختلطة':'درجة الثقة: تقديرية');$('smartSpace').textContent=tr('Geometry + ceiling + lighting candidates linked','تم ربط الهندسة والسقف ومرشحات الإضاءة');if($('approveGeom'))$('approveGeom').checked=false}
function boot(){if(window.KLS_DEEP_READERS_ENABLED===false && window.KLS_GEOMETRY_READER_ENABLED!==true)return;ui();const inp=$('spaceFileNative');if(inp){const f=e=>{const x=e.target.files?.[0];if(x&&(x.type==='application/pdf'||/\.pdf$/i.test(x.name))){file=x;doc=null;result=null;setTimeout(run,3200)}};inp.addEventListener('change',f);inp.addEventListener('input',f)}}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',boot);else boot();
})();